version: 2
jobs:
  develop_build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Pull Submodules
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run:
          name: Chmod permissions
          command: chmod +x gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Generate fabric config
          command: ./gradlew fabricProp
      - run:
          name: Build dev release
          command: ./gradlew assembleDevDebug -PversionCode=$CIRCLE_BUILD_NUM
      - run:
          name: Upload dev release to fabric
          command: ./gradlew crashlyticsUploadDistributionDevDebug
  rc_build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Pull Submodules
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run:
          name: Chmod permissions
          command: chmod +x gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Generate fabric config
          command: ./gradlew fabricProp
      - run:
          name: Build RC
          command: ./gradlew assembleRcRelease -PversionCode=$CIRCLE_BUILD_NUM
      - run:
          name: Upload RC to fabric
          command: ./gradlew crashlyticsUploadDistributionRcRelease
  master_build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Pull Submodules
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run:
          name: Chmod permissions
          command: chmod +x gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Upload Prod build to Google play
          command: ./gradlew publishProdReleaseBundle -PversionCode=$CIRCLE_BUILD_NUM
workflows:
  version: 2
  build_app:
    jobs:
      - develop_build:
          filters:
            branches:
              only: develop
      - master_build:
          filters:
            branches:
              only: master
      - rc_build:
          filters:
            branches:
              only: /rc\/.*/